services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    environment:
       - KC_BOOTSTRAP_ADMIN_USERNAME=admin
       - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    command:
      - start-dev
